#!/usr/bin/python
import sys
from atlasutils.ascii2binary import *

"""
converts binary 0's and 1's into ascii text.  eg.  "01000001" becomes "A"
intended for use inline using stdin/stdout
"""

binary = None
if (len(sys.argv) > 1):
	if (sys.argv[1] == "--test"):
		binary = "0100011101101111011101000010000001010010011101010110110100111111"
	elif (sys.argv[1] == "--help" or sys.argv[1] == "-h"):
		printSyntax()
	else:
		binary = sys.argv[1]
	print(bin2ascii(binary))
else:
	inp = sys.stdin.read()
	try:
		sys.stdout.write(bin2ascii(inp))
	except Exception, e:
		print >>sys.stderr,("Error: %s\nProblems in line %s.  Not binary?  Should look like '011011001010111101010011'"%(e,inp))

