#!/usr/bin/python

"""
converts octal numerical representation into ascii text.  eg.  "101" becomes "A"
intended for use inline using stdin/stdout
"""

import sys
import re

from atlasutils.ascii2octal import *


inputline = sys.stdin.read()
sys.stdout.write(octal2ascii(inputline))

