#!/usr/bin/env python
from base64 import *
from sys import *

"""
decodes data from base64.  When encoding and decoding, be cautious of newlines...
"""

try:
  while (True):
    stdout.write (b64decode(stdin.next()))
except StopIteration, e:
  pass
